version: '3.2'
services:
    redis:
        image: redis
        volumes:
            - redis-data:/data
        ports:
            - 6379:6379

    cmpct:
        build: .
        ports:
            - 80:8080

volumes:
    redis-data:
